# Generated by Django 5.0.1 on 2024-02-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_frist_name_customer_frist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
